### ISSUE TITLE
Deephaven autocomplete

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/vscode-deephaven#68] opened 2024-07-26 19:32 UTC
Autocomplete doesn't seem to be working when I call Deephaven methods. Maybe I don't have VS Code configured properly, but all of my other Python libraries work with autocomplete.

**Comment by bmingles** [comment] 2024-07-29 22:27
@jjbrosnan To get intellisense, you'll need to pip install whatever packages you want to use. A good starting point is:

```
deephaven-core
deephaven-plugin-plotly-express
deephaven-plugin-ui
```

You can always just put this in a `requirements.txt` file in whatever folder you have open in `vscode`. The standard Python extension (not DH) provides some commands to setup virtual environments, install the requirements, etc.

https://code.visualstudio.com/docs/python/python-tutorial

**Comment by alexpeters1208** [comment] 2024-08-06 21:59
FWIW, I'm getting a nonzero amount of autocomplete using pip-installed DH.
<img width="1393" alt="Screenshot 2024-08-06 at 4 58 51 PM" src="https://github.com/user-attachments/assets/8ef76b06-b266-431c-8886-1c880f5a03e0">

**Comment by bmingles** [comment] 2024-09-16 14:06
@jjbrosnan is this still an issue?

**Comment by jjbrosnan** [comment] 2024-09-23 17:59
@bmingles I have yet to re-test. I probably didn't have something configured properly on my end. I'd never used VSCode to write Deephaven queries before.

This can be closed, especially if it's not an issue anyone else has seen.

**Comment by bmingles** [comment] 2024-09-23 19:15
Closing as can't reproduce, and seems to be working for other users.

**Closed by bmingles** 2024-09-23 19:15 UTC
Labels: enhancement
