### ISSUE TITLE
Code available to VS Code and Deephaven Server do not match

### ISSUE THREAD

**Issue by chipkent** [deephaven/vscode-deephaven#44] opened 2024-07-16 18:36 UTC
In remote development in VS Code or JetBrains, the code for the entire project is available in the container.  The current plugin does not behave this way.  Only the executed script is run on the server.  This results in a very awkward workflow for code of any complexity.

Consider this simple example:

`mymod.py`:
```python

print("IN MYMOD")

def myfunc(x):
    return x + 1
```

`main.py`:
```python
import mymod
```

This results in:
```
ava.lang.RuntimeException: Error in Python interpreter:
Type: <class 'ModuleNotFoundError'>
Value: No module named 'mymod'
Line: 1
Namespace: <module>
File: <string>
Traceback (most recent call last):
  File "<string>", line -1, in <module>
```

As a result, python devs have no real way to create multi-file programs.  One reason to move to VS Code is to allow more complex development.  This does not work if multi-file programs are not supported.

**Comment by bmingles** [comment] 2024-07-23 21:41
Closing as duplicate of #10

**Closed by bmingles** 2024-07-23 21:41 UTC
Labels: enhancement, triage
