### ISSUE TITLE
No error is reported if worker fails to start up, connection stays spinning

### ISSUE THREAD

**Issue by mofojed** [deephaven/vscode-deephaven#165] opened 2024-11-01 15:51 UTC
**Description**

If you create a connection but it fails for some reason on the server, then it stays spinning.

**Steps to reproduce**
1. Start a connection to a DHE server where the worker fails (I set heap size to something too big, e.g. 4096gb)

**Expected results**
1. Connection should fail, error should be reported

**Actual results**
1. Connection stays in spinning state, even though on the server can see the worker failed with an error:

![image](https://github.com/user-attachments/assets/4e22842f-1a8d-420d-a3f8-1574fde31589)
![image](https://github.com/user-attachments/assets/3b164d4b-2052-4ac9-b2ba-3f02df5ccc4d)

**Versions**

 v0.1.14-pre release

**Comment by bmingles** [comment] 2024-11-01 17:41
Probably a duplicate of https://github.com/deephaven/vscode-deephaven/issues/158

**Comment by vbabich** [comment] 2024-11-05 16:25
Closing as duplicate

**Closed by vbabich** 2024-11-05 16:25 UTC
Labels: bug, triage
