### ISSUE TITLE
`ClassCastException` in DhcService

### ISSUE THREAD

**Issue by chipkent** [deephaven/vscode-deephaven#41] opened 2024-07-16 18:05 UTC
Deephaven: `Main post 0.35`
Plugin: `1.3.0 pre`

An error popped up when connecting to DH.  Logs were dumped at that point.  It is not clear if the connection triggered the exception.  I was not able to grab the error because it disappeared when i clicked the log dump button.

```
[extension] INFO: Congratulations, your extension "vscode-deephaven" is now active!
[CacheService] INFO: DhcService: caching key: http://localhost:10000/
[DhcService] ERROR: Error: java.lang.ClassCastException
[CacheService] INFO: DhcService: caching key: http://localhost:10000/
[CacheService] INFO: DhcService: caching key: http://localhost:10000/
```

**Comment by vbabich** [comment] 2024-07-24 16:20
We should be logging at least a stack trace if we can't reproduce.

**Comment by bmingles** [comment] 2024-07-24 16:28
@chipkent Do you have any reproduction steps to see the specific error, or was it random?

**Comment by bmingles** [comment] 2024-11-12 23:10
Seems to be a 1 off occurrence, and a lot has changed in the extension since then. Closing this until we see it again / there are reproduction steps.

**Closed by bmingles** 2024-11-12 23:10 UTC
Labels: bug
